# Section 4: Pandas

- Built on NumPy and Matplotlib
- We will use it to import and export data
- Series and DataFrame 
- Series can only contain single list with index. 
- Dataframe is a collection of series

## Pandas Series

In [1]:
import numpy as np
import pandas as pd

In [15]:
mydays = ['Sun', 'Mon', 'Tue']   # Let's create two lists
myexp = [34, 44, 29]

In [16]:
type(myexp)

list

In [17]:
a_mydays = np.array(mydays)
a_myexp = np.array(myexp)

In [5]:
type(a_myexp)

numpy.ndarray

In [6]:
pd.Series(a_myexp)

0    34
1    44
2    29
dtype: int64

In [19]:
pd.Series(myexp)

0    34
1    44
2    29
dtype: int64

In [20]:
pd.Series(a_myexp, a_mydays)

Sun    34
Mon    44
Tue    29
dtype: object

In [12]:
s_myexp = pd.Series(data=a_myexp, index=a_mydays)
s_myexp

Sun    34
Mon    44
Tue    29
dtype: int64

In [11]:
a_myexp[1]   

44

In [16]:
s_myexp[1]

44

In [17]:
s_myexp['Mon'] # my expenses on Monday

44

In [13]:
s_myexp.index

Index(['Sun', 'Mon', 'Tue'], dtype='object')

## Pandas DataFrame

In [8]:
import numpy as np
import pandas as pd

In [9]:
my_nums = np.arange(1,10)
my_nums

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_nums = my_nums.reshape(3,3)
my_nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
pd.DataFrame(my_nums)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [21]:
my_index = ['Row 1', 'Row 2', 'Row 3']

In [22]:
my_col = ['Col 1', 'Col 2', 'Col 3']

In [23]:
df = pd.DataFrame(data=my_nums, index=my_index, columns=my_col)
df

Col 1  Col 2  Col 3
Row 1      1      2      3
Row 2      4      5      6
Row 3      7      8      9

In [24]:
pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['first', 'second', 'third'])

A  B
first   1  4
second  2  5
third   3  6

## Reading a .csv File

In [25]:
import numpy as np
import pandas as pd

In [37]:
df = pd.read_csv('Piece_Dim.csv')

In [38]:
pwd

'/home/ynouros/Desktop/statistics'

In [39]:
df.head()

Item_No  Length  Width  Height Operator
0  Item-1  102.67  49.53   19.69     Op-1
1  Item-2  102.50  51.42   19.63     Op-1
2  Item-3   95.37  52.25   21.51     Op-1
3  Item-4   94.77  49.24   18.60     Op-1
4  Item-5  104.26  47.90   19.46     Op-1

In [40]:
df = pd.read_csv('Piece_Dim.csv', index_col='Item_No' )

In [41]:
df.head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [42]:
df.tail()

Length  Width  Height Operator
Item_No                                
Item-46  101.21  47.61   21.39     Op-2
Item-47  101.09  48.28   20.04     Op-2
Item-48   95.61  46.30   20.31     Op-2
Item-49  104.45  48.71   19.51     Op-2
Item-50   93.28  48.08   19.64     Op-2

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, Item-1 to Item-50
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Length    50 non-null     float64
 1   Width     50 non-null     float64
 2   Height    50 non-null     float64
 3   Operator  50 non-null     object 
dtypes: float64(3), object(1)
memory usage: 2.0+ KB


In [39]:
df.describe()

Length      Width     Height
count   50.000000  50.000000  50.000000
mean   100.128800  49.461400  20.014000
std      5.075593   2.615639   1.074069
min     89.820000  44.460000  17.370000
25%     95.675000  48.105000  19.375000
50%     99.830000  49.315000  19.930000
75%    104.402500  50.780000  20.595000
max    110.540000  55.760000  23.110000

## DataFrame - Dealing with Columns

In [40]:
import numpy as np
import pandas as pd

In [44]:
df = pd.read_csv('Piece_Dim.csv', index_col='Item_No' )

In [45]:
df.head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [56]:
df['Length'].head()

Item_No
Item-1    102.67
Item-2    102.50
Item-3     95.37
Item-4     94.77
Item-5    104.26
Name: Length, dtype: float64

In [96]:
df[['Length']].head()

Length
Item_No        
Item-1   102.67
Item-2   102.50
Item-3    95.37
Item-4    94.77
Item-5   104.26

In [55]:
df[['Length', 'Width']].head()  
# passing a list of columns ['Length', 'Width']
#Look at the first five rows only

Length  Width
Item_No               
Item-1   102.67  49.53
Item-2   102.50  51.42
Item-3    95.37  52.25
Item-4    94.77  49.24
Item-5   104.26  47.90

In [77]:
df['Volume'] = df['Length'] * df['Width'] * df['Height']  
# adding a new column Volume

In [78]:
df.head()

Length  Width  Height Operator         Volume
Item_No                                               
Item-1   102.67  49.53   19.69     Op-1  100128.476019
Item-2   102.50  51.42   19.63     Op-1  103460.896500
Item-3    95.37  52.25   21.51     Op-1  107186.104575
Item-4    94.77  49.24   18.60     Op-1   86796.431280
Item-5   104.26  47.90   19.46     Op-1   97184.290840

In [79]:
np.round(12.22222, 1)

12.2

In [80]:
df['Volume'] = np.round(df['Length'] * df['Width'] * df['Height'],2)

In [81]:
df.head()

Length  Width  Height Operator     Volume
Item_No                                           
Item-1   102.67  49.53   19.69     Op-1  100128.48
Item-2   102.50  51.42   19.63     Op-1  103460.90
Item-3    95.37  52.25   21.51     Op-1  107186.10
Item-4    94.77  49.24   18.60     Op-1   86796.43
Item-5   104.26  47.90   19.46     Op-1   97184.29

In [87]:
df.drop('Volume', axis=1).head()
# You could also use df.drop('Volume', axis='columns')

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [88]:
df.drop('Volume', axis='columns').head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [89]:
df.head() 
#after dropping a column we must save it to a new dataframe else the column will remain

Length  Width  Height Operator     Volume
Item_No                                           
Item-1   102.67  49.53   19.69     Op-1  100128.48
Item-2   102.50  51.42   19.63     Op-1  103460.90
Item-3    95.37  52.25   21.51     Op-1  107186.10
Item-4    94.77  49.24   18.60     Op-1   86796.43
Item-5   104.26  47.90   19.46     Op-1   97184.29

In [90]:
df = df.drop('Volume', axis=1).head() 

In [91]:
df['Volume'] = np.round(df['Length'] * df['Width'] * df['Height'],2)

In [92]:
df.drop('Volume', axis=1, inplace=True)
df.head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

## DataFrame - Dealing with Rows

In [ ]:
import numpy as np
import pandas as pd

In [93]:
df = pd.read_csv('Piece_Dim.csv', index_col='Item_No' )

In [94]:
df.head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [95]:
df.tail()

Length  Width  Height Operator
Item_No                                
Item-46  101.21  47.61   21.39     Op-2
Item-47  101.09  48.28   20.04     Op-2
Item-48   95.61  46.30   20.31     Op-2
Item-49  104.45  48.71   19.51     Op-2
Item-50   93.28  48.08   19.64     Op-2

In [ ]:
#For slicing a DataFrame you need .loc (label based) and .iloc (position based)

### .loc

In [70]:
df.loc['Item-1'] #returns the Series

Length      102.67
Width        49.53
Height       19.69
Operator      Op-1
Name: Item-1, dtype: object

In [72]:
df.loc[['Item-1']] #returns the DataFrame

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1

In [74]:
df.loc[['Item-1', 'Item-5']]

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [75]:
df.loc[['Item-1', 'Item-5'], ['Length', 'Width', 'Height']]

Length  Width  Height
Item_No                       
Item-1   102.67  49.53   19.69
Item-5   104.26  47.90   19.46

### .iloc

In [ ]:
#in .iloc you provide the location

In [68]:
df.iloc[0]

Length      102.67
Width        49.53
Height       19.69
Operator      Op-1
Name: Item-1, dtype: object

In [69]:
df.iloc[[0]]

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1

In [83]:
df.iloc[[0,4],[0,1,2]]

Length  Width  Height
Item_No                       
Item-1   102.67  49.53   19.69
Item-5   104.26  47.90   19.46

In [86]:
df.iloc[:,[0,1,2]].head()   # Here : means all rows

Length  Width  Height
Item_No                       
Item-1   102.67  49.53   19.69
Item-2   102.50  51.42   19.63
Item-3    95.37  52.25   21.51
Item-4    94.77  49.24   18.60
Item-5   104.26  47.90   19.46

In [71]:
df5 = df.iloc[0:5,0:3]  # First five rows and first three columns
df5

Length  Width  Height
Item_No                       
Item-1   102.67  49.53   19.69
Item-2   102.50  51.42   19.63
Item-3    95.37  52.25   21.51
Item-4    94.77  49.24   18.60
Item-5   104.26  47.90   19.46

In [72]:
df5.describe()

Length     Width     Height
count    5.000000   5.00000   5.000000
mean    99.914000  50.06800  19.778000
std      4.479936   1.75102   1.062812
min     94.770000  47.90000  18.600000
25%     95.370000  49.24000  19.460000
50%    102.500000  49.53000  19.630000
75%    102.670000  51.42000  19.690000
max    104.260000  52.25000  21.510000

### Comparision Operator for Selection

In [ ]:
# what we learnt in NumPy

In [96]:
tens = np.arange(0,101,10)  # From 0(included) to 101(excluded) in steps of 10
print(tens)

[  0  10  20  30  40  50  60  70  80  90 100]


In [97]:
tens >= 60  # "boolean mask" is the term for this.

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [98]:
tens[tens >= 60]

array([ 60,  70,  80,  90, 100])

In [99]:
df.head() 
#In a DataFrame you want to have a "feature" in the column and each row should be an instance

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [101]:
df.describe()

Length      Width     Height
count   50.000000  50.000000  50.000000
mean   100.128800  49.461400  20.014000
std      5.075593   2.615639   1.074069
min     89.820000  44.460000  17.370000
25%     95.675000  48.105000  19.375000
50%     99.830000  49.315000  19.930000
75%    104.402500  50.780000  20.595000
max    110.540000  55.760000  23.110000

Case: You want these statistics for just the operator 1.

In [6]:
df1 = df[df['Operator'] == 'Op-1']

In [7]:
df1.describe() # Later in two sample t test you might compare these two operators

Length      Width     Height
count   25.000000  25.000000  25.000000
mean    99.547200  49.301200  20.024800
std      5.147417   2.955796   0.823514
min     89.820000  44.460000  18.600000
25%     95.510000  47.900000  19.510000
50%     98.730000  49.240000  19.940000
75%    104.260000  50.810000  20.360000
max    108.450000  55.760000  22.310000

In [ ]:
# Case: In this example the mean Length is 100.13 and the sd is 5.07. How to you filter items that are more than 105 long?

In [112]:
df[df['Length'] > 105]

Length  Width  Height Operator
Item_No                                
Item-6   105.18  49.39   20.36     Op-1
Item-13  105.72  50.04   20.06     Op-1
Item-17  107.69  48.18   19.33     Op-1
Item-18  106.83  50.81   19.12     Op-1
Item-23  108.45  44.46   22.31     Op-1
Item-27  105.88  49.53   18.70     Op-2
Item-36  105.22  54.61   20.64     Op-2
Item-41  110.54  51.07   21.95     Op-2
Item-42  109.22  45.24   20.05     Op-2
Item-44  107.05  49.01   18.97     Op-2
Item-45  106.53  48.55   19.20     Op-2

In [115]:
df[(df['Length'] > 105) & (df['Operator'] == 'Op-1')]  
# For "and"  use & and for "or" use | 

Length  Width  Height Operator
Item_No                                
Item-6   105.18  49.39   20.36     Op-1
Item-13  105.72  50.04   20.06     Op-1
Item-17  107.69  48.18   19.33     Op-1
Item-18  106.83  50.81   19.12     Op-1
Item-23  108.45  44.46   22.31     Op-1

In [116]:
# STOP *** Try selecting the items with Length between 95 and 105 (both included)

In [120]:
df[(df['Length'] >= 95) & (df['Length'] <= 105)] #Both conditions need to be met

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-5   104.26  47.90   19.46     Op-1
Item-7    97.35  48.05   20.22     Op-1
Item-8    99.35  44.59   21.03     Op-1
Item-10   97.22  52.14   20.71     Op-1
Item-11  100.00  54.76   20.62     Op-1
Item-12   97.23  48.26   19.51     Op-1
Item-15   99.17  53.54   20.25     Op-1
Item-16   95.51  45.36   20.52     Op-1
Item-19   98.73  55.76   19.37     Op-1
Item-21  104.87  49.73   19.94     Op-1
Item-22   98.06  48.39   19.79     Op-1
Item-24   95.34  46.03   20.17     Op-1
Item-25   97.66  50.69   19.54     Op-1
Item-26   95.69  49.48   17.37     Op-2
Item-28  101.68  52.79   19.42     Op-2
Item-30   99.66  48.40   20.64     Op-2
Item-31   98.38  46.79   21.27     Op-2
Item-32   95.53  53.83   23.11     Op-2
Item-33  100.53  50.00   21.13     Op-2
Item-34   95.67  49.64   21.92     Op-2
Item-35  101.86  50.45   18.05     Op-2
Item-37  101.86  49.85   19.15     Op-2
Item-38   97.19  49.90   19.04     Op-2
Item-39  103.00  48.81   19.39     Op-2
Item-40  100.57  53.52   19.98     Op-2
Item-46  101.21  47.61   21.39     Op-2
Item-47  101.09  48.28   20.04     Op-2
Item-48   95.61  46.30   20.31     Op-2
Item-49  104.45  48.71   19.51     Op-2

In [97]:
df[(df['Length'] >= 110) | (df['Width'] <= 45)] #One condition need to be met

Length  Width  Height Operator
Item_No                                
Item-8    99.35  44.59   21.03     Op-1
Item-23  108.45  44.46   22.31     Op-1
Item-41  110.54  51.07   21.95     Op-2

## End of Section
